version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE:      ${DATABASE}
      MYSQL_PASSWORD:      ${ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodo_app
    restart: on-failure
    environment:
      USERDB:        ${USERDB}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
      DATABASE:      ${DATABASE}
      DIALECT:       ${DIALECT}
      HOST:          db
      DB_PORT:       3306
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
